//
// Created by rudolph on 29/3/22.
//

#include <array>

#include "opcode.h"

/// Base timings of each opcode without any page faults or branching
std::array<cycles_t, 256> OPCODE_TIMINGS{
    7, 6, 2, 8, 3, 3, 5, 5, 3, 2, 2, 2, 4, 4, 6, 6, 2, 5, 2, 8, 4, 4, 6, 6,
    2, 4, 2, 7, 4, 4, 7, 7, 6, 6, 2, 8, 3, 3, 5, 5, 4, 2, 2, 2, 4, 4, 6, 6,
    2, 5, 2, 8, 4, 4, 6, 6, 2, 4, 2, 7, 4, 4, 7, 7, 6, 6, 2, 8, 3, 3, 5, 5,
    3, 2, 2, 2, 3, 4, 6, 6, 2, 5, 2, 8, 4, 4, 6, 6, 2, 4, 2, 7, 4, 4, 7, 7,
    6, 6, 2, 8, 3, 3, 5, 5, 4, 2, 2, 2, 5, 4, 6, 6, 2, 5, 2, 8, 4, 4, 6, 6,
    2, 4, 2, 7, 4, 4, 7, 7, 2, 6, 2, 6, 3, 3, 3, 3, 2, 2, 2, 2, 4, 4, 4, 4,
    2, 6, 2, 6, 4, 4, 4, 4, 2, 5, 2, 5, 5, 5, 5, 5, 2, 6, 2, 6, 3, 3, 3, 3,
    2, 2, 2, 2, 4, 4, 4, 4, 2, 5, 2, 5, 4, 4, 4, 4, 2, 4, 2, 4, 4, 4, 4, 4,
    2, 6, 2, 8, 3, 3, 5, 5, 2, 2, 2, 2, 4, 4, 6, 6, 2, 5, 2, 8, 4, 4, 6, 6,
    2, 4, 2, 7, 4, 4, 7, 7, 2, 6, 2, 8, 3, 3, 5, 5, 2, 2, 2, 2, 4, 4, 6, 6,
    2, 5, 2, 8, 4, 4, 6, 6, 2, 4, 2, 7, 4, 4, 7, 7,
};

std::array<Opcode, 256> OPCODES{
    {
        {OpcodeClass::JAM, 0, AddressingMode::Implied, 1, 1},
        {OpcodeClass::JAM, 1, AddressingMode::Implied, 1, 1},
        {OpcodeClass::JAM, 2, AddressingMode::Implied, 1, 1},
        {OpcodeClass::JAM, 3, AddressingMode::Implied, 1, 1},
        {OpcodeClass::JAM, 4, AddressingMode::Implied, 1, 1},
        {OpcodeClass::JAM, 5, AddressingMode::Implied, 1, 1},
        {OpcodeClass::JAM, 6, AddressingMode::Implied, 1, 1},
        {OpcodeClass::JAM, 7, AddressingMode::Implied, 1, 1},
        {OpcodeClass::JAM, 8, AddressingMode::Implied, 1, 1},
        {OpcodeClass::JAM, 9, AddressingMode::Implied, 1, 1},
        {OpcodeClass::JAM, 10, AddressingMode::Implied, 1, 1},
        {OpcodeClass::JAM, 11, AddressingMode::Implied, 1, 1},
        {OpcodeClass::JAM, 12, AddressingMode::Implied, 1, 1},
        {OpcodeClass::JAM, 13, AddressingMode::Implied, 1, 1},
        {OpcodeClass::JAM, 14, AddressingMode::Implied, 1, 1},
        {OpcodeClass::JAM, 15, AddressingMode::Implied, 1, 1},
        {OpcodeClass::JAM, 16, AddressingMode::Implied, 1, 1},
        {OpcodeClass::JAM, 17, AddressingMode::Implied, 1, 1},
        {OpcodeClass::JAM, 18, AddressingMode::Implied, 1, 1},
        {OpcodeClass::JAM, 19, AddressingMode::Implied, 1, 1},
        {OpcodeClass::JAM, 20, AddressingMode::Implied, 1, 1},
        {OpcodeClass::JAM, 21, AddressingMode::Implied, 1, 1},
        {OpcodeClass::JAM, 22, AddressingMode::Implied, 1, 1},
        {OpcodeClass::JAM, 23, AddressingMode::Implied, 1, 1},
        {OpcodeClass::JAM, 24, AddressingMode::Implied, 1, 1},
        {OpcodeClass::JAM, 25, AddressingMode::Implied, 1, 1},
        {OpcodeClass::JAM, 26, AddressingMode::Implied, 1, 1},
        {OpcodeClass::JAM, 27, AddressingMode::Implied, 1, 1},
        {OpcodeClass::JAM, 28, AddressingMode::Implied, 1, 1},
        {OpcodeClass::JAM, 29, AddressingMode::Implied, 1, 1},
        {OpcodeClass::JAM, 30, AddressingMode::Implied, 1, 1},
        {OpcodeClass::JAM, 31, AddressingMode::Implied, 1, 1},
        {OpcodeClass::JAM, 32, AddressingMode::Implied, 1, 1},
        {OpcodeClass::JAM, 33, AddressingMode::Implied, 1, 1},
        {OpcodeClass::JAM, 34, AddressingMode::Implied, 1, 1},
        {OpcodeClass::JAM, 35, AddressingMode::Implied, 1, 1},
        {OpcodeClass::JAM, 36, AddressingMode::Implied, 1, 1},
        {OpcodeClass::JAM, 37, AddressingMode::Implied, 1, 1},
        {OpcodeClass::JAM, 38, AddressingMode::Implied, 1, 1},
        {OpcodeClass::JAM, 39, AddressingMode::Implied, 1, 1},
        {OpcodeClass::JAM, 40, AddressingMode::Implied, 1, 1},
        {OpcodeClass::JAM, 41, AddressingMode::Implied, 1, 1},
        {OpcodeClass::JAM, 42, AddressingMode::Implied, 1, 1},
        {OpcodeClass::JAM, 43, AddressingMode::Implied, 1, 1},
        {OpcodeClass::JAM, 44, AddressingMode::Implied, 1, 1},
        {OpcodeClass::JAM, 45, AddressingMode::Implied, 1, 1},
        {OpcodeClass::JAM, 46, AddressingMode::Implied, 1, 1},
        {OpcodeClass::JAM, 47, AddressingMode::Implied, 1, 1},
        {OpcodeClass::JAM, 48, AddressingMode::Implied, 1, 1},
        {OpcodeClass::JAM, 49, AddressingMode::Implied, 1, 1},
        {OpcodeClass::JAM, 50, AddressingMode::Implied, 1, 1},
        {OpcodeClass::JAM, 51, AddressingMode::Implied, 1, 1},
        {OpcodeClass::JAM, 52, AddressingMode::Implied, 1, 1},
        {OpcodeClass::JAM, 53, AddressingMode::Implied, 1, 1},
        {OpcodeClass::JAM, 54, AddressingMode::Implied, 1, 1},
        {OpcodeClass::JAM, 55, AddressingMode::Implied, 1, 1},
        {OpcodeClass::JAM, 56, AddressingMode::Implied, 1, 1},
        {OpcodeClass::JAM, 57, AddressingMode::Implied, 1, 1},
        {OpcodeClass::JAM, 58, AddressingMode::Implied, 1, 1},
        {OpcodeClass::JAM, 59, AddressingMode::Implied, 1, 1},
        {OpcodeClass::JAM, 60, AddressingMode::Implied, 1, 1},
        {OpcodeClass::JAM, 61, AddressingMode::Implied, 1, 1},
        {OpcodeClass::JAM, 62, AddressingMode::Implied, 1, 1},
        {OpcodeClass::JAM, 63, AddressingMode::Implied, 1, 1},
        {OpcodeClass::JAM, 64, AddressingMode::Implied, 1, 1},
        {OpcodeClass::JAM, 65, AddressingMode::Implied, 1, 1},
        {OpcodeClass::JAM, 66, AddressingMode::Implied, 1, 1},
        {OpcodeClass::JAM, 67, AddressingMode::Implied, 1, 1},
        {OpcodeClass::JAM, 68, AddressingMode::Implied, 1, 1},
        {OpcodeClass::JAM, 69, AddressingMode::Implied, 1, 1},
        {OpcodeClass::JAM, 70, AddressingMode::Implied, 1, 1},
        {OpcodeClass::JAM, 71, AddressingMode::Implied, 1, 1},
        {OpcodeClass::JAM, 72, AddressingMode::Implied, 1, 1},
        {OpcodeClass::JAM, 73, AddressingMode::Implied, 1, 1},
        {OpcodeClass::JAM, 74, AddressingMode::Implied, 1, 1},
        {OpcodeClass::JAM, 75, AddressingMode::Implied, 1, 1},
        {OpcodeClass::JMP, 76, AddressingMode::Absolute, 3, 3},
        {OpcodeClass::JAM, 77, AddressingMode::Implied, 1, 1},
        {OpcodeClass::JAM, 78, AddressingMode::Implied, 1, 1},
        {OpcodeClass::JAM, 79, AddressingMode::Implied, 1, 1},
        {OpcodeClass::JAM, 80, AddressingMode::Implied, 1, 1},
        {OpcodeClass::JAM, 81, AddressingMode::Implied, 1, 1},
        {OpcodeClass::JAM, 82, AddressingMode::Implied, 1, 1},
        {OpcodeClass::JAM, 83, AddressingMode::Implied, 1, 1},
        {OpcodeClass::JAM, 84, AddressingMode::Implied, 1, 1},
        {OpcodeClass::JAM, 85, AddressingMode::Implied, 1, 1},
        {OpcodeClass::JAM, 86, AddressingMode::Implied, 1, 1},
        {OpcodeClass::JAM, 87, AddressingMode::Implied, 1, 1},
        {OpcodeClass::JAM, 88, AddressingMode::Implied, 1, 1},
        {OpcodeClass::JAM, 89, AddressingMode::Implied, 1, 1},
        {OpcodeClass::JAM, 90, AddressingMode::Implied, 1, 1},
        {OpcodeClass::JAM, 91, AddressingMode::Implied, 1, 1},
        {OpcodeClass::JAM, 92, AddressingMode::Implied, 1, 1},
        {OpcodeClass::JAM, 93, AddressingMode::Implied, 1, 1},
        {OpcodeClass::JAM, 94, AddressingMode::Implied, 1, 1},
        {OpcodeClass::JAM, 95, AddressingMode::Implied, 1, 1},
        {OpcodeClass::JAM, 96, AddressingMode::Implied, 1, 1},
        {OpcodeClass::JAM, 97, AddressingMode::Implied, 1, 1},
        {OpcodeClass::JAM, 98, AddressingMode::Implied, 1, 1},
        {OpcodeClass::JAM, 99, AddressingMode::Implied, 1, 1},
        {OpcodeClass::JAM, 100, AddressingMode::Implied, 1, 1},
        {OpcodeClass::JAM, 101, AddressingMode::Implied, 1, 1},
        {OpcodeClass::JAM, 102, AddressingMode::Implied, 1, 1},
        {OpcodeClass::JAM, 103, AddressingMode::Implied, 1, 1},
        {OpcodeClass::JAM, 104, AddressingMode::Implied, 1, 1},
        {OpcodeClass::JAM, 105, AddressingMode::Implied, 1, 1},
        {OpcodeClass::JAM, 106, AddressingMode::Implied, 1, 1},
        {OpcodeClass::JAM, 107, AddressingMode::Implied, 1, 1},
        {OpcodeClass::JMP, 108, AddressingMode::Indirect, 3, 5},
        {OpcodeClass::JAM, 109, AddressingMode::Implied, 1, 1},
        {OpcodeClass::JAM, 110, AddressingMode::Implied, 1, 1},
        {OpcodeClass::JAM, 111, AddressingMode::Implied, 1, 1},
        {OpcodeClass::JAM, 112, AddressingMode::Implied, 1, 1},
        {OpcodeClass::JAM, 113, AddressingMode::Implied, 1, 1},
        {OpcodeClass::JAM, 114, AddressingMode::Implied, 1, 1},
        {OpcodeClass::JAM, 115, AddressingMode::Implied, 1, 1},
        {OpcodeClass::JAM, 116, AddressingMode::Implied, 1, 1},
        {OpcodeClass::JAM, 117, AddressingMode::Implied, 1, 1},
        {OpcodeClass::JAM, 118, AddressingMode::Implied, 1, 1},
        {OpcodeClass::JAM, 119, AddressingMode::Implied, 1, 1},
        {OpcodeClass::JAM, 120, AddressingMode::Implied, 1, 1},
        {OpcodeClass::JAM, 121, AddressingMode::Implied, 1, 1},
        {OpcodeClass::JAM, 122, AddressingMode::Implied, 1, 1},
        {OpcodeClass::JAM, 123, AddressingMode::Implied, 1, 1},
        {OpcodeClass::JAM, 124, AddressingMode::Implied, 1, 1},
        {OpcodeClass::JAM, 125, AddressingMode::Implied, 1, 1},
        {OpcodeClass::JAM, 126, AddressingMode::Implied, 1, 1},
        {OpcodeClass::JAM, 127, AddressingMode::Implied, 1, 1},
        {OpcodeClass::JAM, 128, AddressingMode::Implied, 1, 1},
        {OpcodeClass::JAM, 129, AddressingMode::Implied, 1, 1},
        {OpcodeClass::JAM, 130, AddressingMode::Implied, 1, 1},
        {OpcodeClass::JAM, 131, AddressingMode::Implied, 1, 1},
        {OpcodeClass::JAM, 132, AddressingMode::Implied, 1, 1},
        {OpcodeClass::JAM, 133, AddressingMode::Implied, 1, 1},
        {OpcodeClass::JAM, 134, AddressingMode::Implied, 1, 1},
        {OpcodeClass::JAM, 135, AddressingMode::Implied, 1, 1},
        {OpcodeClass::JAM, 136, AddressingMode::Implied, 1, 1},
        {OpcodeClass::JAM, 137, AddressingMode::Implied, 1, 1},
        {OpcodeClass::JAM, 138, AddressingMode::Implied, 1, 1},
        {OpcodeClass::JAM, 139, AddressingMode::Implied, 1, 1},
        {OpcodeClass::JAM, 140, AddressingMode::Implied, 1, 1},
        {OpcodeClass::JAM, 141, AddressingMode::Implied, 1, 1},
        {OpcodeClass::JAM, 142, AddressingMode::Implied, 1, 1},
        {OpcodeClass::JAM, 143, AddressingMode::Implied, 1, 1},
        {OpcodeClass::JAM, 144, AddressingMode::Implied, 1, 1},
        {OpcodeClass::JAM, 145, AddressingMode::Implied, 1, 1},
        {OpcodeClass::JAM, 146, AddressingMode::Implied, 1, 1},
        {OpcodeClass::JAM, 147, AddressingMode::Implied, 1, 1},
        {OpcodeClass::JAM, 148, AddressingMode::Implied, 1, 1},
        {OpcodeClass::JAM, 149, AddressingMode::Implied, 1, 1},
        {OpcodeClass::JAM, 150, AddressingMode::Implied, 1, 1},
        {OpcodeClass::JAM, 151, AddressingMode::Implied, 1, 1},
        {OpcodeClass::JAM, 152, AddressingMode::Implied, 1, 1},
        {OpcodeClass::JAM, 153, AddressingMode::Implied, 1, 1},
        {OpcodeClass::JAM, 154, AddressingMode::Implied, 1, 1},
        {OpcodeClass::JAM, 155, AddressingMode::Implied, 1, 1},
        {OpcodeClass::JAM, 156, AddressingMode::Implied, 1, 1},
        {OpcodeClass::JAM, 157, AddressingMode::Implied, 1, 1},
        {OpcodeClass::JAM, 158, AddressingMode::Implied, 1, 1},
        {OpcodeClass::JAM, 159, AddressingMode::Implied, 1, 1},
        {OpcodeClass::JAM, 160, AddressingMode::Implied, 1, 1},
        {OpcodeClass::JAM, 161, AddressingMode::Implied, 1, 1},
        {OpcodeClass::LDX, 162, AddressingMode::Immediate, 2, 2},
        {OpcodeClass::JAM, 163, AddressingMode::Implied, 1, 1},
        {OpcodeClass::JAM, 164, AddressingMode::Implied, 1, 1},
        {OpcodeClass::JAM, 165, AddressingMode::Implied, 1, 1},
        {OpcodeClass::LDX, 166, AddressingMode::ZeroPage, 2, 3},
        {OpcodeClass::JAM, 167, AddressingMode::Implied, 1, 1},
        {OpcodeClass::JAM, 168, AddressingMode::Implied, 1, 1},
        {OpcodeClass::JAM, 169, AddressingMode::Implied, 1, 1},
        {OpcodeClass::JAM, 170, AddressingMode::Implied, 1, 1},
        {OpcodeClass::JAM, 171, AddressingMode::Implied, 1, 1},
        {OpcodeClass::JAM, 172, AddressingMode::Implied, 1, 1},
        {OpcodeClass::JAM, 173, AddressingMode::Implied, 1, 1},
        {OpcodeClass::LDX, 174, AddressingMode::Absolute, 3, 4},
        {OpcodeClass::JAM, 175, AddressingMode::Implied, 1, 1},
        {OpcodeClass::JAM, 176, AddressingMode::Implied, 1, 1},
        {OpcodeClass::JAM, 177, AddressingMode::Implied, 1, 1},
        {OpcodeClass::JAM, 178, AddressingMode::Implied, 1, 1},
        {OpcodeClass::JAM, 179, AddressingMode::Implied, 1, 1},
        {OpcodeClass::JAM, 180, AddressingMode::Implied, 1, 1},
        {OpcodeClass::JAM, 181, AddressingMode::Implied, 1, 1},
        {OpcodeClass::LDX, 182, AddressingMode::ZeroPageY, 2, 4},
        {OpcodeClass::JAM, 183, AddressingMode::Implied, 1, 1},
        {OpcodeClass::JAM, 184, AddressingMode::Implied, 1, 1},
        {OpcodeClass::JAM, 185, AddressingMode::Implied, 1, 1},
        {OpcodeClass::JAM, 186, AddressingMode::Implied, 1, 1},
        {OpcodeClass::JAM, 187, AddressingMode::Implied, 1, 1},
        {OpcodeClass::JAM, 188, AddressingMode::Implied, 1, 1},
        {OpcodeClass::JAM, 189, AddressingMode::Implied, 1, 1},
        {OpcodeClass::LDX, 190, AddressingMode::AbsoluteYIndexed, 3, 4},
        {OpcodeClass::JAM, 191, AddressingMode::Implied, 1, 1},
        {OpcodeClass::JAM, 192, AddressingMode::Implied, 1, 1},
        {OpcodeClass::JAM, 193, AddressingMode::Implied, 1, 1},
        {OpcodeClass::JAM, 194, AddressingMode::Implied, 1, 1},
        {OpcodeClass::JAM, 195, AddressingMode::Implied, 1, 1},
        {OpcodeClass::JAM, 196, AddressingMode::Implied, 1, 1},
        {OpcodeClass::JAM, 197, AddressingMode::Implied, 1, 1},
        {OpcodeClass::JAM, 198, AddressingMode::Implied, 1, 1},
        {OpcodeClass::JAM, 199, AddressingMode::Implied, 1, 1},
        {OpcodeClass::JAM, 200, AddressingMode::Implied, 1, 1},
        {OpcodeClass::JAM, 201, AddressingMode::Implied, 1, 1},
        {OpcodeClass::JAM, 202, AddressingMode::Implied, 1, 1},
        {OpcodeClass::JAM, 203, AddressingMode::Implied, 1, 1},
        {OpcodeClass::JAM, 204, AddressingMode::Implied, 1, 1},
        {OpcodeClass::JAM, 205, AddressingMode::Implied, 1, 1},
        {OpcodeClass::JAM, 206, AddressingMode::Implied, 1, 1},
        {OpcodeClass::JAM, 207, AddressingMode::Implied, 1, 1},
        {OpcodeClass::JAM, 208, AddressingMode::Implied, 1, 1},
        {OpcodeClass::JAM, 209, AddressingMode::Implied, 1, 1},
        {OpcodeClass::JAM, 210, AddressingMode::Implied, 1, 1},
        {OpcodeClass::JAM, 211, AddressingMode::Implied, 1, 1},
        {OpcodeClass::JAM, 212, AddressingMode::Implied, 1, 1},
        {OpcodeClass::JAM, 213, AddressingMode::Implied, 1, 1},
        {OpcodeClass::JAM, 214, AddressingMode::Implied, 1, 1},
        {OpcodeClass::JAM, 215, AddressingMode::Implied, 1, 1},
        {OpcodeClass::JAM, 216, AddressingMode::Implied, 1, 1},
        {OpcodeClass::JAM, 217, AddressingMode::Implied, 1, 1},
        {OpcodeClass::JAM, 218, AddressingMode::Implied, 1, 1},
        {OpcodeClass::JAM, 219, AddressingMode::Implied, 1, 1},
        {OpcodeClass::JAM, 220, AddressingMode::Implied, 1, 1},
        {OpcodeClass::JAM, 221, AddressingMode::Implied, 1, 1},
        {OpcodeClass::JAM, 222, AddressingMode::Implied, 1, 1},
        {OpcodeClass::JAM, 223, AddressingMode::Implied, 1, 1},
        {OpcodeClass::JAM, 224, AddressingMode::Implied, 1, 1},
        {OpcodeClass::JAM, 225, AddressingMode::Implied, 1, 1},
        {OpcodeClass::JAM, 226, AddressingMode::Implied, 1, 1},
        {OpcodeClass::JAM, 227, AddressingMode::Implied, 1, 1},
        {OpcodeClass::JAM, 228, AddressingMode::Implied, 1, 1},
        {OpcodeClass::JAM, 229, AddressingMode::Implied, 1, 1},
        {OpcodeClass::JAM, 230, AddressingMode::Implied, 1, 1},
        {OpcodeClass::JAM, 231, AddressingMode::Implied, 1, 1},
        {OpcodeClass::JAM, 232, AddressingMode::Implied, 1, 1},
        {OpcodeClass::JAM, 233, AddressingMode::Implied, 1, 1},
        {OpcodeClass::JAM, 234, AddressingMode::Implied, 1, 1},
        {OpcodeClass::JAM, 235, AddressingMode::Implied, 1, 1},
        {OpcodeClass::JAM, 236, AddressingMode::Implied, 1, 1},
        {OpcodeClass::JAM, 237, AddressingMode::Implied, 1, 1},
        {OpcodeClass::JAM, 238, AddressingMode::Implied, 1, 1},
        {OpcodeClass::JAM, 239, AddressingMode::Implied, 1, 1},
        {OpcodeClass::JAM, 240, AddressingMode::Implied, 1, 1},
        {OpcodeClass::JAM, 241, AddressingMode::Implied, 1, 1},
        {OpcodeClass::JAM, 242, AddressingMode::Implied, 1, 1},
        {OpcodeClass::JAM, 243, AddressingMode::Implied, 1, 1},
        {OpcodeClass::JAM, 244, AddressingMode::Implied, 1, 1},
        {OpcodeClass::JAM, 245, AddressingMode::Implied, 1, 1},
        {OpcodeClass::JAM, 246, AddressingMode::Implied, 1, 1},
        {OpcodeClass::JAM, 247, AddressingMode::Implied, 1, 1},
        {OpcodeClass::JAM, 248, AddressingMode::Implied, 1, 1},
        {OpcodeClass::JAM, 249, AddressingMode::Implied, 1, 1},
        {OpcodeClass::JAM, 250, AddressingMode::Implied, 1, 1},
        {OpcodeClass::JAM, 251, AddressingMode::Implied, 1, 1},
        {OpcodeClass::JAM, 252, AddressingMode::Implied, 1, 1},
        {OpcodeClass::JAM, 253, AddressingMode::Implied, 1, 1},
        {OpcodeClass::JAM, 254, AddressingMode::Implied, 1, 1},
        {OpcodeClass::JAM, 255, AddressingMode::Implied, 1, 1},
    },
};

Opcode DecodeOpcode(byte opcode) {
    return OPCODES.at(opcode);
}
