//
// Created by rudolph on 29/3/22.
//

#include <array>

#include "opcode.h"

/// Base timings of each opcode without any page faults or branching
std::array<cycles_t, 256> OPCODE_TIMINGS{
    7, 6, 2, 8, 3, 3, 5, 5, 3, 2, 2, 2, 4, 4, 6, 6, 2, 5, 2, 8, 4, 4, 6, 6,
    2, 4, 2, 7, 4, 4, 7, 7, 6, 6, 2, 8, 3, 3, 5, 5, 4, 2, 2, 2, 4, 4, 6, 6,
    2, 5, 2, 8, 4, 4, 6, 6, 2, 4, 2, 7, 4, 4, 7, 7, 6, 6, 2, 8, 3, 3, 5, 5,
    3, 2, 2, 2, 3, 4, 6, 6, 2, 5, 2, 8, 4, 4, 6, 6, 2, 4, 2, 7, 4, 4, 7, 7,
    6, 6, 2, 8, 3, 3, 5, 5, 4, 2, 2, 2, 5, 4, 6, 6, 2, 5, 2, 8, 4, 4, 6, 6,
    2, 4, 2, 7, 4, 4, 7, 7, 2, 6, 2, 6, 3, 3, 3, 3, 2, 2, 2, 2, 4, 4, 4, 4,
    2, 6, 2, 6, 4, 4, 4, 4, 2, 5, 2, 5, 5, 5, 5, 5, 2, 6, 2, 6, 3, 3, 3, 3,
    2, 2, 2, 2, 4, 4, 4, 4, 2, 5, 2, 5, 4, 4, 4, 4, 2, 4, 2, 4, 4, 4, 4, 4,
    2, 6, 2, 8, 3, 3, 5, 5, 2, 2, 2, 2, 4, 4, 6, 6, 2, 5, 2, 8, 4, 4, 6, 6,
    2, 4, 2, 7, 4, 4, 7, 7, 2, 6, 2, 8, 3, 3, 5, 5, 2, 2, 2, 2, 4, 4, 6, 6,
    2, 5, 2, 8, 4, 4, 6, 6, 2, 4, 2, 7, 4, 4, 7, 7,
};

std::array<Opcode, 256> OPCODES{
    {
        {OpcodeClass::JAM, 0x0, AddressingMode::Implied, 1, 1},
        {OpcodeClass::ORA, 0x1, AddressingMode::IndirectX, 2, 6},
        {OpcodeClass::JAM, 0x2, AddressingMode::Implied, 1, 1},
        {OpcodeClass::JAM, 0x3, AddressingMode::Implied, 1, 1},
        {OpcodeClass::JAM, 0x4, AddressingMode::Implied, 1, 1},
        {OpcodeClass::ORA, 0x5, AddressingMode::ZeroPage, 2, 3},
        {OpcodeClass::JAM, 0x6, AddressingMode::Implied, 1, 1},
        {OpcodeClass::JAM, 0x7, AddressingMode::Implied, 1, 1},
        {OpcodeClass::PHP, 0x8, AddressingMode::Implied, 1, 3},
        {OpcodeClass::ORA, 0x9, AddressingMode::Immediate, 2, 2},
        {OpcodeClass::JAM, 0xA, AddressingMode::Implied, 1, 1},
        {OpcodeClass::JAM, 0xB, AddressingMode::Implied, 1, 1},
        {OpcodeClass::JAM, 0xC, AddressingMode::Implied, 1, 1},
        {OpcodeClass::ORA, 0xD, AddressingMode::Absolute, 3, 4},
        {OpcodeClass::JAM, 0xE, AddressingMode::Implied, 1, 1},
        {OpcodeClass::JAM, 0xF, AddressingMode::Implied, 1, 1},
        {OpcodeClass::BPL, 0x10, AddressingMode::Relative, 2, 2},
        {OpcodeClass::ORA, 0x11, AddressingMode::IndirectY, 2, 5},
        {OpcodeClass::JAM, 0x12, AddressingMode::Implied, 1, 1},
        {OpcodeClass::JAM, 0x13, AddressingMode::Implied, 1, 1},
        {OpcodeClass::JAM, 0x14, AddressingMode::Implied, 1, 1},
        {OpcodeClass::ORA, 0x15, AddressingMode::ZeroPageX, 2, 4},
        {OpcodeClass::JAM, 0x16, AddressingMode::Implied, 1, 1},
        {OpcodeClass::JAM, 0x17, AddressingMode::Implied, 1, 1},
        {OpcodeClass::CLC, 0x18, AddressingMode::Implied, 1, 2},
        {OpcodeClass::ORA, 0x19, AddressingMode::AbsoluteYIndexed, 3, 4},
        {OpcodeClass::JAM, 0x1A, AddressingMode::Implied, 1, 1},
        {OpcodeClass::JAM, 0x1B, AddressingMode::Implied, 1, 1},
        {OpcodeClass::JAM, 0x1C, AddressingMode::Implied, 1, 1},
        {OpcodeClass::ORA, 0x1D, AddressingMode::AbsoluteXIndexed, 3, 4},
        {OpcodeClass::JAM, 0x1E, AddressingMode::Implied, 1, 1},
        {OpcodeClass::JAM, 0x1F, AddressingMode::Implied, 1, 1},
        {OpcodeClass::JSR, 0x20, AddressingMode::Absolute, 3, 6},
        {OpcodeClass::AND, 0x21, AddressingMode::IndirectX, 2, 6},
        {OpcodeClass::JAM, 0x22, AddressingMode::Implied, 1, 1},
        {OpcodeClass::JAM, 0x23, AddressingMode::Implied, 1, 1},
        {OpcodeClass::BIT, 0x24, AddressingMode::ZeroPage, 2, 3},
        {OpcodeClass::AND, 0x25, AddressingMode::ZeroPage, 2, 3},
        {OpcodeClass::JAM, 0x26, AddressingMode::Implied, 1, 1},
        {OpcodeClass::JAM, 0x27, AddressingMode::Implied, 1, 1},
        {OpcodeClass::PLP, 0x28, AddressingMode::Implied, 1, 4},
        {OpcodeClass::AND, 0x29, AddressingMode::Immediate, 2, 2},
        {OpcodeClass::JAM, 0x2A, AddressingMode::Implied, 1, 1},
        {OpcodeClass::JAM, 0x2B, AddressingMode::Implied, 1, 1},
        {OpcodeClass::BIT, 0x2C, AddressingMode::Absolute, 3, 4},
        {OpcodeClass::AND, 0x2D, AddressingMode::Absolute, 3, 4},
        {OpcodeClass::JAM, 0x2E, AddressingMode::Implied, 1, 1},
        {OpcodeClass::JAM, 0x2F, AddressingMode::Implied, 1, 1},
        {OpcodeClass::BMI, 0x30, AddressingMode::Relative, 2, 2},
        {OpcodeClass::AND, 0x31, AddressingMode::IndirectY, 2, 5},
        {OpcodeClass::JAM, 0x32, AddressingMode::Implied, 1, 1},
        {OpcodeClass::JAM, 0x33, AddressingMode::Implied, 1, 1},
        {OpcodeClass::JAM, 0x34, AddressingMode::Implied, 1, 1},
        {OpcodeClass::AND, 0x35, AddressingMode::ZeroPageX, 2, 4},
        {OpcodeClass::JAM, 0x36, AddressingMode::Implied, 1, 1},
        {OpcodeClass::JAM, 0x37, AddressingMode::Implied, 1, 1},
        {OpcodeClass::SEC, 0x38, AddressingMode::Implied, 1, 2},
        {OpcodeClass::AND, 0x39, AddressingMode::AbsoluteYIndexed, 3, 4},
        {OpcodeClass::JAM, 0x3A, AddressingMode::Implied, 1, 1},
        {OpcodeClass::JAM, 0x3B, AddressingMode::Implied, 1, 1},
        {OpcodeClass::JAM, 0x3C, AddressingMode::Implied, 1, 1},
        {OpcodeClass::AND, 0x3D, AddressingMode::AbsoluteXIndexed, 3, 4},
        {OpcodeClass::JAM, 0x3E, AddressingMode::Implied, 1, 1},
        {OpcodeClass::JAM, 0x3F, AddressingMode::Implied, 1, 1},
        {OpcodeClass::JAM, 0x40, AddressingMode::Implied, 1, 1},
        {OpcodeClass::EOR, 0x41, AddressingMode::IndirectX, 2, 6},
        {OpcodeClass::JAM, 0x42, AddressingMode::Implied, 1, 1},
        {OpcodeClass::JAM, 0x43, AddressingMode::Implied, 1, 1},
        {OpcodeClass::JAM, 0x44, AddressingMode::Implied, 1, 1},
        {OpcodeClass::EOR, 0x45, AddressingMode::ZeroPage, 2, 3},
        {OpcodeClass::JAM, 0x46, AddressingMode::Implied, 1, 1},
        {OpcodeClass::JAM, 0x47, AddressingMode::Implied, 1, 1},
        {OpcodeClass::PHA, 0x48, AddressingMode::Implied, 1, 3},
        {OpcodeClass::EOR, 0x49, AddressingMode::Immediate, 2, 2},
        {OpcodeClass::JAM, 0x4A, AddressingMode::Implied, 1, 1},
        {OpcodeClass::JAM, 0x4B, AddressingMode::Implied, 1, 1},
        {OpcodeClass::JMP, 0x4C, AddressingMode::Absolute, 3, 3},
        {OpcodeClass::EOR, 0x4D, AddressingMode::Absolute, 3, 4},
        {OpcodeClass::JAM, 0x4E, AddressingMode::Implied, 1, 1},
        {OpcodeClass::JAM, 0x4F, AddressingMode::Implied, 1, 1},
        {OpcodeClass::BVC, 0x50, AddressingMode::Relative, 2, 2},
        {OpcodeClass::EOR, 0x51, AddressingMode::IndirectY, 2, 5},
        {OpcodeClass::JAM, 0x52, AddressingMode::Implied, 1, 1},
        {OpcodeClass::JAM, 0x53, AddressingMode::Implied, 1, 1},
        {OpcodeClass::JAM, 0x54, AddressingMode::Implied, 1, 1},
        {OpcodeClass::EOR, 0x55, AddressingMode::ZeroPageX, 2, 4},
        {OpcodeClass::JAM, 0x56, AddressingMode::Implied, 1, 1},
        {OpcodeClass::JAM, 0x57, AddressingMode::Implied, 1, 1},
        {OpcodeClass::JAM, 0x58, AddressingMode::Implied, 1, 1},
        {OpcodeClass::EOR, 0x59, AddressingMode::AbsoluteYIndexed, 3, 4},
        {OpcodeClass::JAM, 0x5A, AddressingMode::Implied, 1, 1},
        {OpcodeClass::JAM, 0x5B, AddressingMode::Implied, 1, 1},
        {OpcodeClass::JAM, 0x5C, AddressingMode::Implied, 1, 1},
        {OpcodeClass::EOR, 0x5D, AddressingMode::AbsoluteXIndexed, 3, 4},
        {OpcodeClass::JAM, 0x5E, AddressingMode::Implied, 1, 1},
        {OpcodeClass::JAM, 0x5F, AddressingMode::Implied, 1, 1},
        {OpcodeClass::RTS, 0x60, AddressingMode::Implied, 1, 6},
        {OpcodeClass::JAM, 0x61, AddressingMode::Implied, 1, 1},
        {OpcodeClass::JAM, 0x62, AddressingMode::Implied, 1, 1},
        {OpcodeClass::JAM, 0x63, AddressingMode::Implied, 1, 1},
        {OpcodeClass::JAM, 0x64, AddressingMode::Implied, 1, 1},
        {OpcodeClass::JAM, 0x65, AddressingMode::Implied, 1, 1},
        {OpcodeClass::JAM, 0x66, AddressingMode::Implied, 1, 1},
        {OpcodeClass::JAM, 0x67, AddressingMode::Implied, 1, 1},
        {OpcodeClass::PLA, 0x68, AddressingMode::Implied, 1, 4},
        {OpcodeClass::JAM, 0x69, AddressingMode::Implied, 1, 1},
        {OpcodeClass::JAM, 0x6A, AddressingMode::Implied, 1, 1},
        {OpcodeClass::JAM, 0x6B, AddressingMode::Implied, 1, 1},
        {OpcodeClass::JMP, 0x6C, AddressingMode::Indirect, 3, 5},
        {OpcodeClass::JAM, 0x6D, AddressingMode::Implied, 1, 1},
        {OpcodeClass::JAM, 0x6E, AddressingMode::Implied, 1, 1},
        {OpcodeClass::JAM, 0x6F, AddressingMode::Implied, 1, 1},
        {OpcodeClass::BVS, 0x70, AddressingMode::Relative, 2, 2},
        {OpcodeClass::JAM, 0x71, AddressingMode::Implied, 1, 1},
        {OpcodeClass::JAM, 0x72, AddressingMode::Implied, 1, 1},
        {OpcodeClass::JAM, 0x73, AddressingMode::Implied, 1, 1},
        {OpcodeClass::JAM, 0x74, AddressingMode::Implied, 1, 1},
        {OpcodeClass::JAM, 0x75, AddressingMode::Implied, 1, 1},
        {OpcodeClass::JAM, 0x76, AddressingMode::Implied, 1, 1},
        {OpcodeClass::JAM, 0x77, AddressingMode::Implied, 1, 1},
        {OpcodeClass::SEI, 0x78, AddressingMode::Implied, 1, 2},
        {OpcodeClass::JAM, 0x79, AddressingMode::Implied, 1, 1},
        {OpcodeClass::JAM, 0x7A, AddressingMode::Implied, 1, 1},
        {OpcodeClass::JAM, 0x7B, AddressingMode::Implied, 1, 1},
        {OpcodeClass::JAM, 0x7C, AddressingMode::Implied, 1, 1},
        {OpcodeClass::JAM, 0x7D, AddressingMode::Implied, 1, 1},
        {OpcodeClass::JAM, 0x7E, AddressingMode::Implied, 1, 1},
        {OpcodeClass::JAM, 0x7F, AddressingMode::Implied, 1, 1},
        {OpcodeClass::JAM, 0x80, AddressingMode::Implied, 1, 1},
        {OpcodeClass::STA, 0x81, AddressingMode::IndirectX, 2, 6},
        {OpcodeClass::JAM, 0x82, AddressingMode::Implied, 1, 1},
        {OpcodeClass::JAM, 0x83, AddressingMode::Implied, 1, 1},
        {OpcodeClass::JAM, 0x84, AddressingMode::Implied, 1, 1},
        {OpcodeClass::STA, 0x85, AddressingMode::ZeroPage, 2, 3},
        {OpcodeClass::STX, 0x86, AddressingMode::ZeroPage, 2, 3},
        {OpcodeClass::JAM, 0x87, AddressingMode::Implied, 1, 1},
        {OpcodeClass::JAM, 0x88, AddressingMode::Implied, 1, 1},
        {OpcodeClass::JAM, 0x89, AddressingMode::Implied, 1, 1},
        {OpcodeClass::JAM, 0x8A, AddressingMode::Implied, 1, 1},
        {OpcodeClass::JAM, 0x8B, AddressingMode::Implied, 1, 1},
        {OpcodeClass::JAM, 0x8C, AddressingMode::Implied, 1, 1},
        {OpcodeClass::STA, 0x8D, AddressingMode::Absolute, 3, 4},
        {OpcodeClass::STX, 0x8E, AddressingMode::Absolute, 3, 4},
        {OpcodeClass::JAM, 0x8F, AddressingMode::Implied, 1, 1},
        {OpcodeClass::BCC, 0x90, AddressingMode::Relative, 2, 2},
        {OpcodeClass::STA, 0x91, AddressingMode::IndirectY, 2, 6},
        {OpcodeClass::JAM, 0x92, AddressingMode::Implied, 1, 1},
        {OpcodeClass::JAM, 0x93, AddressingMode::Implied, 1, 1},
        {OpcodeClass::JAM, 0x94, AddressingMode::Implied, 1, 1},
        {OpcodeClass::STA, 0x95, AddressingMode::ZeroPageX, 2, 4},
        {OpcodeClass::STX, 0x96, AddressingMode::ZeroPageY, 2, 4},
        {OpcodeClass::JAM, 0x97, AddressingMode::Implied, 1, 1},
        {OpcodeClass::JAM, 0x98, AddressingMode::Implied, 1, 1},
        {OpcodeClass::STA, 0x99, AddressingMode::AbsoluteYIndexed, 3, 5},
        {OpcodeClass::JAM, 0x9A, AddressingMode::Implied, 1, 1},
        {OpcodeClass::JAM, 0x9B, AddressingMode::Implied, 1, 1},
        {OpcodeClass::JAM, 0x9C, AddressingMode::Implied, 1, 1},
        {OpcodeClass::STA, 0x9D, AddressingMode::AbsoluteXIndexed, 3, 5},
        {OpcodeClass::JAM, 0x9E, AddressingMode::Implied, 1, 1},
        {OpcodeClass::JAM, 0x9F, AddressingMode::Implied, 1, 1},
        {OpcodeClass::JAM, 0xA0, AddressingMode::Implied, 1, 1},
        {OpcodeClass::LDA, 0xA1, AddressingMode::IndirectX, 2, 6},
        {OpcodeClass::LDX, 0xA2, AddressingMode::Immediate, 2, 2},
        {OpcodeClass::JAM, 0xA3, AddressingMode::Implied, 1, 1},
        {OpcodeClass::JAM, 0xA4, AddressingMode::Implied, 1, 1},
        {OpcodeClass::LDA, 0xA5, AddressingMode::ZeroPage, 2, 3},
        {OpcodeClass::LDX, 0xA6, AddressingMode::ZeroPage, 2, 3},
        {OpcodeClass::JAM, 0xA7, AddressingMode::Implied, 1, 1},
        {OpcodeClass::JAM, 0xA8, AddressingMode::Implied, 1, 1},
        {OpcodeClass::LDA, 0xA9, AddressingMode::Immediate, 2, 2},
        {OpcodeClass::JAM, 0xAA, AddressingMode::Implied, 1, 1},
        {OpcodeClass::JAM, 0xAB, AddressingMode::Implied, 1, 1},
        {OpcodeClass::JAM, 0xAC, AddressingMode::Implied, 1, 1},
        {OpcodeClass::LDA, 0xAD, AddressingMode::Absolute, 3, 4},
        {OpcodeClass::LDX, 0xAE, AddressingMode::Absolute, 3, 4},
        {OpcodeClass::JAM, 0xAF, AddressingMode::Implied, 1, 1},
        {OpcodeClass::BCS, 0xB0, AddressingMode::Relative, 2, 2},
        {OpcodeClass::LDA, 0xB1, AddressingMode::IndirectY, 2, 5},
        {OpcodeClass::JAM, 0xB2, AddressingMode::Implied, 1, 1},
        {OpcodeClass::JAM, 0xB3, AddressingMode::Implied, 1, 1},
        {OpcodeClass::JAM, 0xB4, AddressingMode::Implied, 1, 1},
        {OpcodeClass::LDA, 0xB5, AddressingMode::ZeroPageX, 2, 4},
        {OpcodeClass::LDX, 0xB6, AddressingMode::ZeroPageY, 2, 4},
        {OpcodeClass::JAM, 0xB7, AddressingMode::Implied, 1, 1},
        {OpcodeClass::CLV, 0xB8, AddressingMode::Implied, 1, 2},
        {OpcodeClass::LDA, 0xB9, AddressingMode::AbsoluteYIndexed, 3, 4},
        {OpcodeClass::JAM, 0xBA, AddressingMode::Implied, 1, 1},
        {OpcodeClass::JAM, 0xBB, AddressingMode::Implied, 1, 1},
        {OpcodeClass::JAM, 0xBC, AddressingMode::Implied, 1, 1},
        {OpcodeClass::LDA, 0xBD, AddressingMode::AbsoluteXIndexed, 3, 4},
        {OpcodeClass::LDX, 0xBE, AddressingMode::AbsoluteYIndexed, 3, 4},
        {OpcodeClass::JAM, 0xBF, AddressingMode::Implied, 1, 1},
        {OpcodeClass::JAM, 0xC0, AddressingMode::Implied, 1, 1},
        {OpcodeClass::CMP, 0xC1, AddressingMode::IndirectX, 2, 6},
        {OpcodeClass::JAM, 0xC2, AddressingMode::Implied, 1, 1},
        {OpcodeClass::JAM, 0xC3, AddressingMode::Implied, 1, 1},
        {OpcodeClass::JAM, 0xC4, AddressingMode::Implied, 1, 1},
        {OpcodeClass::CMP, 0xC5, AddressingMode::ZeroPage, 2, 3},
        {OpcodeClass::JAM, 0xC6, AddressingMode::Implied, 1, 1},
        {OpcodeClass::JAM, 0xC7, AddressingMode::Implied, 1, 1},
        {OpcodeClass::JAM, 0xC8, AddressingMode::Implied, 1, 1},
        {OpcodeClass::CMP, 0xC9, AddressingMode::Immediate, 2, 2},
        {OpcodeClass::JAM, 0xCA, AddressingMode::Implied, 1, 1},
        {OpcodeClass::JAM, 0xCB, AddressingMode::Implied, 1, 1},
        {OpcodeClass::JAM, 0xCC, AddressingMode::Implied, 1, 1},
        {OpcodeClass::CMP, 0xCD, AddressingMode::Absolute, 3, 4},
        {OpcodeClass::JAM, 0xCE, AddressingMode::Implied, 1, 1},
        {OpcodeClass::JAM, 0xCF, AddressingMode::Implied, 1, 1},
        {OpcodeClass::BNE, 0xD0, AddressingMode::Relative, 2, 2},
        {OpcodeClass::CMP, 0xD1, AddressingMode::IndirectY, 2, 5},
        {OpcodeClass::JAM, 0xD2, AddressingMode::Implied, 1, 1},
        {OpcodeClass::JAM, 0xD3, AddressingMode::Implied, 1, 1},
        {OpcodeClass::JAM, 0xD4, AddressingMode::Implied, 1, 1},
        {OpcodeClass::CMP, 0xD5, AddressingMode::ZeroPageX, 2, 4},
        {OpcodeClass::JAM, 0xD6, AddressingMode::Implied, 1, 1},
        {OpcodeClass::JAM, 0xD7, AddressingMode::Implied, 1, 1},
        {OpcodeClass::CLD, 0xD8, AddressingMode::Implied, 1, 2},
        {OpcodeClass::CMP, 0xD9, AddressingMode::AbsoluteYIndexed, 3, 4},
        {OpcodeClass::JAM, 0xDA, AddressingMode::Implied, 1, 1},
        {OpcodeClass::JAM, 0xDB, AddressingMode::Implied, 1, 1},
        {OpcodeClass::JAM, 0xDC, AddressingMode::Implied, 1, 1},
        {OpcodeClass::CMP, 0xDD, AddressingMode::AbsoluteXIndexed, 3, 4},
        {OpcodeClass::JAM, 0xDE, AddressingMode::Implied, 1, 1},
        {OpcodeClass::JAM, 0xDF, AddressingMode::Implied, 1, 1},
        {OpcodeClass::JAM, 0xE0, AddressingMode::Implied, 1, 1},
        {OpcodeClass::JAM, 0xE1, AddressingMode::Implied, 1, 1},
        {OpcodeClass::JAM, 0xE2, AddressingMode::Implied, 1, 1},
        {OpcodeClass::JAM, 0xE3, AddressingMode::Implied, 1, 1},
        {OpcodeClass::JAM, 0xE4, AddressingMode::Implied, 1, 1},
        {OpcodeClass::JAM, 0xE5, AddressingMode::Implied, 1, 1},
        {OpcodeClass::JAM, 0xE6, AddressingMode::Implied, 1, 1},
        {OpcodeClass::JAM, 0xE7, AddressingMode::Implied, 1, 1},
        {OpcodeClass::JAM, 0xE8, AddressingMode::Implied, 1, 1},
        {OpcodeClass::JAM, 0xE9, AddressingMode::Implied, 1, 1},
        {OpcodeClass::NOP, 0xEA, AddressingMode::Implied, 1, 2},
        {OpcodeClass::JAM, 0xEB, AddressingMode::Implied, 1, 1},
        {OpcodeClass::JAM, 0xEC, AddressingMode::Implied, 1, 1},
        {OpcodeClass::JAM, 0xED, AddressingMode::Implied, 1, 1},
        {OpcodeClass::JAM, 0xEE, AddressingMode::Implied, 1, 1},
        {OpcodeClass::JAM, 0xEF, AddressingMode::Implied, 1, 1},
        {OpcodeClass::BEQ, 0xF0, AddressingMode::Relative, 2, 2},
        {OpcodeClass::JAM, 0xF1, AddressingMode::Implied, 1, 1},
        {OpcodeClass::JAM, 0xF2, AddressingMode::Implied, 1, 1},
        {OpcodeClass::JAM, 0xF3, AddressingMode::Implied, 1, 1},
        {OpcodeClass::JAM, 0xF4, AddressingMode::Implied, 1, 1},
        {OpcodeClass::JAM, 0xF5, AddressingMode::Implied, 1, 1},
        {OpcodeClass::JAM, 0xF6, AddressingMode::Implied, 1, 1},
        {OpcodeClass::JAM, 0xF7, AddressingMode::Implied, 1, 1},
        {OpcodeClass::SED, 0xF8, AddressingMode::Implied, 1, 2},
        {OpcodeClass::JAM, 0xF9, AddressingMode::Implied, 1, 1},
        {OpcodeClass::JAM, 0xFA, AddressingMode::Implied, 1, 1},
        {OpcodeClass::JAM, 0xFB, AddressingMode::Implied, 1, 1},
        {OpcodeClass::JAM, 0xFC, AddressingMode::Implied, 1, 1},
        {OpcodeClass::JAM, 0xFD, AddressingMode::Implied, 1, 1},
        {OpcodeClass::JAM, 0xFE, AddressingMode::Implied, 1, 1},
        {OpcodeClass::JAM, 0xFF, AddressingMode::Implied, 1, 1},
    },
};

Opcode DecodeOpcode(byte opcode) {
    return OPCODES.at(opcode);
}
